# Server Port
server.port=8080

# Spring Application Name
spring.application.name=quangtrung-bank-backend


spring.datasource.url=jdbc:mysql://localhost:3306/quangtrung_bank?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=123456

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL Script Execution Settings (Runs schema.sql and data.sql)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.quangtrungbank=DEBUG

# Jackson Date/Time GMT+7 configuration
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

